$('.tech_list').eq(0).on('mouseover',function(){
    $('.tech').eq(0).css('display','flex');
    $('.tech').eq(0).siblings().css('display','none');
});
$('.tech_list').eq(0).on('mouseout',function(){
    $('.tech').eq(0).css('display','flex');
    $('.tech').eq(0).siblings().css('display','none');
});
$('.tech_list').eq(1).on('mouseover',function(){
    $('.tech').eq(1).css('display','flex');
    $('.tech').eq(1).siblings().css('display','none');
});
$('.tech_list').eq(1).on('mouseout',function(){
    $('.tech').eq(1).css('display','flex');
    $('.tech').eq(1).siblings().css('display','none');
});
$('.tech_list').eq(2).on('mouseover',function(){
    $('.tech').eq(2).css('display','flex');
    $('.tech').eq(2).siblings().css('display','none');
});
$('.tech_list').eq(2).on('mouseout',function(){
    $('.tech').eq(2).css('display','flex');
    $('.tech').eq(2).siblings().css('display','none');
});
$('.tech_list').eq(3).on('mouseover',function(){
    $('.tech').eq(3).css('display','flex');
    $('.tech').eq(3).siblings().css('display','none');
});
$('.tech_list').eq(3).on('mouseout',function(){
    $('.tech').eq(3).css('display','flex');
    $('.tech').eq(3).siblings().css('display','none');
});